apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
spec:
  selector:
    matchLabels:
      app: nginx
      role: green
  template:
    metadata:
      labels:
        app: nginx
        role: green
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
