apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: nginx
    role: blue
    env: production
spec:
  type: LoadBalancer
  selector:
    app: nginx
    role: green
  ports:
  - port: 80
    targetPort: 80
