apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: nginx
    tier: frontend
spec:
  replicas: 1 # default number of replicas is 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers: 
      - name: nginx
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
