apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    tier: frontend
  ports:
  - name: "80"
    port: 80
    targetPort: 80
